package com.proyecto.favseries;

import android.content.Context;

public class FavSeriesApplication_Objects {
	
	public static FavSeriesApplication[] arrayObjetos(Context contexto){
		FavSeriesApplication array[] = {
				new FavSeriesApplication(contexto.getString(R.string.anatomiaGrey),
						contexto.getString(R.string.anatomiaGreySinopsis),
						R.drawable.anatomiagreybanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
					"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
					"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
					"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
					"Temporada 24", "Temporada 25",}, 
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.arrow),
							contexto.getString(R.string.arrowSinopsis),
							R.drawable.arrowbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
						"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
						"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
						"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
						"Temporada 24", "Temporada 25",}, 
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),	
					
					
				new FavSeriesApplication(contexto.getString(R.string.bones),
						contexto.getString(R.string.bonesSinopsis),
						R.drawable.bonesbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.breaking),
						contexto.getString(R.string.breakingSinopsis),
						R.drawable.breakingbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.calico),
						contexto.getString(R.string.calicoSinopsis),
						R.drawable.calicobanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
					new FavSeriesApplication(contexto.getString(R.string.castle),
							contexto.getString(R.string.castleSinopsis),
							R.drawable.castlebanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),		
			
				new FavSeriesApplication(contexto.getString(R.string.comoconoci),
						contexto.getString(R.string.comoconociSinopsis),
						R.drawable.comoconocibanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.dexter),
						contexto.getString(R.string.dexterSinopsis),
						R.drawable.dexterbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.doshombresymedio),
							contexto.getString(R.string.doshombresymedioSinopsis),
							R.drawable.doshombresymediobanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.equipoa),
						contexto.getString(R.string.equipoaSinopsis),
						R.drawable.equipoabanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
					new FavSeriesApplication(contexto.getString(R.string.eraseunavez),
							contexto.getString(R.string.eraseunavezSinopsis),
							R.drawable.eraseunavezbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),		
			
				new FavSeriesApplication(contexto.getString(R.string.family),
						contexto.getString(R.string.familySinopsis),
						R.drawable.familyguybanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.friends),
						contexto.getString(R.string.friendsSinopsis),
						R.drawable.friendsbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.fringe),
							contexto.getString(R.string.fringeSinopsis),
							R.drawable.fringebanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
						
				new FavSeriesApplication(contexto.getString(R.string.futurama),
						contexto.getString(R.string.futuramaSinopsis),
						R.drawable.futuramabanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.gossip),
						contexto.getString(R.string.gossipSinopsis),
						R.drawable.gossipbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.heidi),
						contexto.getString(R.string.heidiSinopsis),
						R.drawable.heidibanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.homeland),
							contexto.getString(R.string.homelandSinopsis),
							R.drawable.homelandbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.house),
						contexto.getString(R.string.houseSinopsis),
						R.drawable.housebanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.imperium),
						contexto.getString(R.string.imperiumSinopsis),
						R.drawable.imperiumbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.jericho),
						contexto.getString(R.string.jerichoSinopsis),
						R.drawable.jerichobanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.juego),
						contexto.getString(R.string.juegoSinopsis),
						R.drawable.tronosbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.kim),
						contexto.getString(R.string.kimSinopsis),
						R.drawable.kimbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.simpson),
						contexto.getString(R.string.simpsonSinopsis),
						R.drawable.simpsonbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.mentes),
							contexto.getString(R.string.mentesSinopsis),
							R.drawable.mentesbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.modernfamily),
						contexto.getString(R.string.modernfamilySinopsis),
						R.drawable.modernfamilybanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.mujeres),
						contexto.getString(R.string.mujeresSinopsis),
						R.drawable.desperatebanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.naruto),
						contexto.getString(R.string.narutoSinopsis),
						R.drawable.narutobanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.revenge),
						contexto.getString(R.string.revengeSinopsis),
						R.drawable.revengebanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
			
					new FavSeriesApplication(contexto.getString(R.string.southpark),
							contexto.getString(R.string.southparkSinopsis),
							R.drawable.southparkbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),	
				
				new FavSeriesApplication(contexto.getString(R.string.spartacus),
						contexto.getString(R.string.spartacusSinopsis),
						R.drawable.spartacusbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.supernatural),
						contexto.getString(R.string.supernaturalSinopsis),
						R.drawable.supernaturalbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.bigbang),
						contexto.getString(R.string.bigbangSinopsis),
						R.drawable.bigbangbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
					
					new FavSeriesApplication(contexto.getString(R.string.thementalist),
							contexto.getString(R.string.thementalistSinopsis),
							R.drawable.thementalistbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				new FavSeriesApplication(contexto.getString(R.string.walking),
						contexto.getString(R.string.walkingSinopsis),
						R.drawable.wakingdeadbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"})
		};

		return array;
	}
	
	
	
	
	public static FavSeriesApplication[] arrayObjetos2(Context contexto){
		FavSeriesApplication array2[] = {
				
				new FavSeriesApplication(contexto.getString(R.string.juego),
						contexto.getString(R.string.juegoSinopsis),
						R.drawable.tronosbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
					new FavSeriesApplication(contexto.getString(R.string.friends),
							contexto.getString(R.string.friendsSinopsis),
							R.drawable.friendsbanner, 
							new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
							new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
						"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
						"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
						"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
						"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
						"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),		
			
				new FavSeriesApplication(contexto.getString(R.string.comoconoci),
						contexto.getString(R.string.comoconociSinopsis),
						R.drawable.comoconocibanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
						
			new FavSeriesApplication(contexto.getString(R.string.bigbang),
								contexto.getString(R.string.bigbangSinopsis),
								R.drawable.bigbangbanner, 
								new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
				"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
				"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
				"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
				"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
				"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
						
			new FavSeriesApplication(contexto.getString(R.string.house),
								contexto.getString(R.string.houseSinopsis),
								R.drawable.housebanner, 
								new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
				"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 10", "Capitulo 11", "Capitulo 12",
				"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
				"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
				"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
				"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
				
				new FavSeriesApplication(contexto.getString(R.string.gossip),
						contexto.getString(R.string.gossipSinopsis),
						R.drawable.gossipbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 11", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
						
			new FavSeriesApplication(contexto.getString(R.string.modernfamily),
								contexto.getString(R.string.modernfamilySinopsis),
								R.drawable.modernfamilybanner, 
								new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
				"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 11", "Capitulo 11", "Capitulo 12",
				"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
				"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
				"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
				"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
			new FavSeriesApplication(contexto.getString(R.string.mujeres),
										contexto.getString(R.string.mujeresSinopsis),
										R.drawable.desperatebanner, 
										new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
										new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
				"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 11", "Capitulo 11", "Capitulo 12",
				"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
				"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
				"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
				"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),
				
            new FavSeriesApplication(contexto.getString(R.string.walking),
												contexto.getString(R.string.walkingSinopsis),
												R.drawable.wakingdeadbanner, 
												new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
				"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
				"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
				"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
				"Temporada 24", "Temporada 25",},  
										new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
				"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 11", "Capitulo 11", "Capitulo 12",
				"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
				"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
				"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
				"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"}),	
				
		
				new FavSeriesApplication(contexto.getString(R.string.simpson),
						contexto.getString(R.string.simpsonSinopsis),
						R.drawable.simpsonbanner, 
						new String[]{"Temporada 1", "Temporada 2", "Temporada 3", "Temporada 4", "Temporada 5",
			"Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9", "Temporada 10", "Temporada 11",
			"Temporada 12", "Temporada 13", "Temporada 14", "Temporada 15", "Temporada 16", "Temporada 17", 
			"Temporada 18", "Temporada 19", "Temporada 20", "Temporada 21", "Temporada 22", "Temporada 23", 
			"Temporada 24", "Temporada 25",},  
						new String[]{"Capitulo 1", "Capitulo 2", "Capitulo 3", "Capitulo 4", "Capitulo 5",
					"Capitulo 6", "Capitulo 7", "Capitulo 8", "Capitulo 9", "Capitulo 11", "Capitulo 11", "Capitulo 12",
					"Capitulo 13", "Capitulo 14", "Capitulo 15", "Capitulo 16", "Capitulo 17", "Capitulo 18", "Capitulo 19",
					"Capitulo 20", "Capitulo 21", "Capitulo 22", "Capitulo 23", "Capitulo 24", "Capitulo 25", "Capitulo 26",
					"Capitulo 27", "Capitulo 28", "Capitulo 29", "Capitulo 30", "Capitulo 31", "Capitulo 32", "Capitulo 33",
					"Capitulo 34", "Capitulo 35", "Capitulo 36", "Capitulo 37", "Capitulo 38", "Capitulo 39", "Capitulo 40"})
				
			
				
		};

		return array2;
	}

}
